import React from "react";
import SuperAdminLayout from "../../Components/SuperAdminLayout";
import { Bot, PlayCircle, LineChart, Sliders, UploadCloud } from "lucide-react";

const AIModelManagement = () => {
  return (
    <SuperAdminLayout>
      <div className="space-y-10">
        {/* PAGE TITLE */}
        <h1 className="text-3xl font-bold text-gray-800 flex items-center gap-3">
          <Bot size={30} /> AI Model Management
        </h1>

        {/* 1️⃣ TRAIN AI SECTION */}
        <section className="bg-white p-6 rounded-xl shadow space-y-4">
          <h2 className="text-xl font-semibold text-gray-700 flex items-center gap-2">
            <PlayCircle className="text-blue-600" /> Train AI Model
          </h2>

          <p className="text-gray-600">
            Upload new datasets or retrain the AI model with updated institution data.
          </p>

          <div className="flex items-center gap-4">
            <input
              type="file"
              className="border border-gray-300 p-2 rounded-lg"
            />

            <button className="px-5 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700">
              Upload Dataset
            </button>

            <button className="px-5 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700">
              Start Training
            </button>
          </div>
        </section>

        {/* 2️⃣ AI Predictions Monitoring */}
        <section className="bg-white p-6 rounded-xl shadow space-y-4">
          <h2 className="text-xl font-semibold text-gray-700 flex items-center gap-2">
            <LineChart className="text-purple-600" /> AI Predictions Monitoring
          </h2>

          <p className="text-gray-600">
            Track the accuracy, risks, and confidence levels generated by the AI model.
          </p>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mt-4">
            <div className="p-4 bg-purple-100 text-purple-800 rounded-xl shadow">
              <h3 className="text-lg font-semibold">Accuracy</h3>
              <p className="text-3xl font-bold mt-2">91%</p>
            </div>

            <div className="p-4 bg-yellow-100 text-yellow-800 rounded-xl shadow">
              <h3 className="text-lg font-semibold">Risk Alerts</h3>
              <p className="text-3xl font-bold mt-2">7</p>
            </div>

            <div className="p-4 bg-blue-100 text-blue-800 rounded-xl shadow">
              <h3 className="text-lg font-semibold">Confidence Score</h3>
              <p className="text-3xl font-bold mt-2">0.87</p>
            </div>
          </div>
        </section>

        {/* 3️⃣ AI Scoring Criteria Tuning */}
        <section className="bg-white p-6 rounded-xl shadow space-y-6">
          <h2 className="text-xl font-semibold text-gray-700 flex items-center gap-2">
            <Sliders className="text-green-600" /> Tune AI Scoring Criteria
          </h2>

          <p className="text-gray-600">
            Adjust how heavily each factor influences the AI scoring.
          </p>

          <div className="space-y-4">
            {/* Faculty Weight */}
            <div>
              <label className="text-gray-700 font-medium">
                Faculty Quality Weight
              </label>
              <input
                type="range"
                min="0"
                max="100"
                defaultValue="60"
                className="w-full mt-2"
              />
            </div>

            {/* Infrastructure Weight */}
            <div>
              <label className="text-gray-700 font-medium">
                Infrastructure Weight
              </label>
              <input
                type="range"
                min="0"
                max="100"
                defaultValue="75"
                className="w-full mt-2"
              />
            </div>

            {/* Placement Weight */}
            <div>
              <label className="text-gray-700 font-medium">
                Placement Score Weight
              </label>
              <input
                type="range"
                min="0"
                max="100"
                defaultValue="82"
                className="w-full mt-2"
              />
            </div>
          </div>

          <button className="px-5 py-2 bg-indigo-600 text-white rounded-lg hover:bg-indigo-700">
            Save Scoring Updates
          </button>
        </section>
      </div>
    </SuperAdminLayout>
  );
};

export default AIModelManagement;
